(defun halve(a) (/ a 2))
(defun double(a) (+ a a))
(defun even?(n) (= (mod n 2) 0))

(defun mult(a b)
  (defun iter-mult(a b r)
    (cond ((= b 0) r)
	  ((even? b) (iter-mult (double a) (halve b) r))
	  (t (iter-mult a (- b 1) (+ a r)))))
  (iter-mult a b 0))
